
# Clash 核心配置文件 (iOS 端使用)
# 配置节点、策略组和规则

mixed-port: 7890         # 同时开启 http 和 socks5 代理端口，端口号 7890
allow-lan: true          # 是否允许局域网其他设备访问（iOS 一般无影响，默认 true 即可）
mode: rule               # 代理模式: rule=规则模式, global=全局代理, direct=直连
log-level: info          # 日志等级: info=正常, debug=调试(更详细日志), error=仅错误

keep-alive-interval: 15  # TCP 保活心跳间隔(秒)，避免长时间无流量断开
tcp-concurrent: true     # 是否启用 TCP 并发连接，可以提升访问速度

proxies:                 # 节点配置列表
  - name: "我的节点"       # 节点名称，自定义，后面在 proxy-groups 中引用
    type: vmess           # 节点类型，支持 vmess/vless/trojan/ss 等
    server: your.server.com # 节点服务器地址，需要替换为真实服务器
    port: 443             # 节点端口号，一般为 443/80
    uuid: xxxxx-xxxx-xxxx-xxxx # 节点的 UUID，需要替换为真实值
    alterId: 0            # 额外 ID，V2Ray 新版通常为 0
    cipher: auto          # 加密方式，auto 即自动选择
    tls: true             # 是否启用 TLS 加密

proxy-groups:            # 策略组配置，用于节点选择和规则引用
  - name: "Proxy"         # 策略组名称
    type: select          # 策略组类型: select=手动选择, url-test/ fallback/ load-balance 等
    proxies:
      - "我的节点"        # 引用上面定义的节点

rules:                   # 分流规则
  - GEOIP,CN,DIRECT       # 中国大陆 IP 直连
  - MATCH,Proxy           # 其他所有流量都走 Proxy 策略组